[package]

name = "tftp"
version = "0.1.0-pre"
authors = ["arjan.top@gmail.com"]

[lib]

name = "tftp"
path = "src/tftp/lib.rs"

[[example]]

name = "get"
path = "examples/client/get.rs"

[[example]]

name = "put"
path = "examples/client/put.rs"

[dependencies]

byteorder = "*"
mio = "*"
bytes = "*"

[dev-dependencies]

quickcheck = "*"
quickcheck_macros = "*"
rand = "*"
