[package]

name = "tftp"
version = "0.1.0-pre"
authors = ["arjan.top@gmail.com"]

[lib]

name = "tftp"
path = "src/tftp/lib.rs"

[[example]]

name = "client-get"
path = "examples/client/get.rs"

[[example]]

name = "client-put"
path = "examples/client/put.rs"

[dev-dependencies]

quickcheck = "~0.2.0"
quickcheck_macros = "~0.2.0"
rand = "~0.1.0"
